# Generated by Django 6.0.5 on 2026-05-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=10, unique=True)),
                ('student_branch', models.CharField(max_length=50)),
                ('student_contact', models.CharField(max_length=10)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='students/')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
    ]
