# Generated by Django 6.0.5 on 2026-05-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Teacher'},
        ),
    ]
